name: Continuous Integration - Reusable
on: [workflow_call]
jobs:
  CI_Steps:
    runs-on: [self-hosted]
    steps:
      - name: Code checkout
        uses: actions/checkout@v4
      - run: echo OK
        name: Code Lint
#      - run: echo OK
#        name: Code Build
      - run: npm run test:unit
        name: Code Unit Test
      - run: npm run test:integration
        name: Code Integration Test
      - run: echo OK
        name: Code Review
      - run: echo OK
        name: Release Software



