name: Release - Reusable
on:
  workflow_call:
    inputs:
      project_name:
        required: true
        type: string
#      release_archive_file:
#        required: true
#        type: string
      npm_install:
        required: true
        type: boolean
    secrets:
      vault_token:
        required: true
jobs:
  CI_Steps:
    runs-on: [self-hosted]
    steps:
      - name: Code checkout
        uses: actions/checkout@v4

      - run: echo npm install
        name: Install Nodejs module
        if: ${{ inputs.npm_install }}
        
      - name: Import Vault Secrets
        id: vault-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: https://vault.ramdevops78.online:8200/
          token: ${{ secrets.vault_token }}
          tlsSkipVerify: true
          secrets: |
            common/data/common artifactory_user | artifactory_user;
            common/data/common artifactory_password | artifactory_password ;     

      - run: ${{ GITHUB_REF_NAME }} >VERSION
        name: Create Version File

      - run: zip -r artifact.zip ${{ inputs.project_name }}
        name: Create Zip file
#     - run: curl -v --user ${{ steps.vault-secrets.outputs.artifactory_user }}:${{ steps.vault-secrets.outputs.artifactory_password }} --data-binary @$artifact.zip -X PUT "http://artifactory-internal.ramdevops78.online:8081/artifactory/${{ inputs.project_name }}/@${{ GITHUB_REF_NAME }}.zip"

